spring.application.name=User-Service
jwt.secretKey=abcdefghrhbnklmzxcv89bnmzxcvbnm123456
server.port=8081
spring.datasource.url=jdbc:postgresql://localhost:5432/UserDB
spring.datasource.username=postgres
spring.datasource.password=Sonu@1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
