spring.application.name=User-Service
jwt.secretKey=abcdefghrhbnklmzxcv89bnmzxcvbnm123456
server.port=8081
spring.datasource.url=jdbc:postgresql://localhost:5432/userDB
spring.datasource.username=postgres
spring.datasource.password=Sonu@1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
eureka.client.service-url.defaultZone=http://localhost:9091/eureka/
server.servlet.context-path=/user
