spring.application.name=Post-Service
server.port=9190

spring.datasource.url=jdbc:postgresql://localhost:5432/LinkedinApp
spring.datasource.username=postgres
spring.datasource.password=Sonu@1234
spring.jpa.hibernate.ddl-auto=update
